### ISSUE TITLE
Display favicons in Bookmark toolbar

### ISSUE THREAD

**Issue by sivapvarma** [ideaweb/firefox-safari-style#11]
Stock firefox

![](https://i.imgur.com/hdub0Wv.png)

vs github master on Firefox nightly

![](https://i.imgur.com/bhInltj.png)

Thanks for your amazing work on this project.

**Comment by ideaweb** [comment]
I got already requests to remove the icons that it is more closer to Safari. That's why i would let it as is and suggest you to check [this issue](https://github.com/ideaweb/firefox-safari-style/issues/8) howto restore the icons.

**Comment by ideaweb** [comment]
Added code snippet to "Extras" in Readme.
