### ISSUE TITLE
Weird top padding on fullscreen videos

### ISSUE THREAD

**Issue by kgorol** [ideaweb/firefox-safari-style#14]
![AB3-D418-C-766-E-4-E99-9124-B65-B3617-EE78](https://user-images.githubusercontent.com/34159482/89991377-0ec7f280-dc84-11ea-999b-28c1010782d9.jpg)

Example above :)

**Comment by jodelkoenig** [comment]
I can confirm this error. Firefox 80.0.1; macos 10.15.6. Thanks

**Comment by ideaweb** [comment]
Fixed... please update.

**Comment by jodelkoenig** [comment]
confirmed ... thanks ideaweb, a very cool theme!
