### ISSUE TITLE
Hide tab bar when there's only one tab

### ISSUE THREAD

**Issue by Silly511** [ideaweb/firefox-safari-style#15]
In Safari when there's only one tab open the tab bar is hidden. The add tab button moves up to the bookmarks bar when the tab bar is hidden. With this style the tab bar is always shown, even if there's only one tab.

**Comment by ideaweb** [comment]
Problem is, this theme uses CSS for styling only. With CSS i cannot add or change any functionality in Firefox. But of course i could detect an empty container with CSS but in Firefox the container for tabs is not really empty if all tabs are closed, there are still hidden tabs with recent closed tabs (e.g. for undoing). Thats why i cannot detect it. Maybe i found a workaround and thats why i let this issue open, e.g. container can collapse automatically. 

Please do not forget, the goal is that Firefox looks like macOS, but not to change its own functionality. Firefox is Firefox and Safari is Safari.

**Comment by Silly511** [comment]
Yeah, after I created this issue I tried to find a way to implement it myself but I ran into the same problem you described. I left the issue open in case you knew some way to do it that I hadn't seen.

**Comment by ideaweb** [comment]
Found a workaround. Please update your code and check the new section "Extras" in Readme to enable it.
