### ISSUE TITLE
Black flickering on some websites (especially when videos are playing)

### ISSUE THREAD

**Issue by tskucik** [ideaweb/firefox-safari-style#16]
This issue is mostly noticeable on Twitter (but I've noticed it on other sites like YouTube), whenever I scroll down and there's a tweet with a video, the entire site starts to flicker with a black background. It looks like this:

<img width="1397" alt="obraz" src="https://user-images.githubusercontent.com/35234463/96234625-f59c3480-0f99-11eb-9df2-7fd589cd932b.png">

It's only like this in windowed mode, when I enter fullscreen mode the problem disappears.

I've tried disabling all my extensions, but that didn't change anything. The problem disappears only when I remove the theme.

I'm on Firefox 81.0.2, MacOS Catalina 10.15.7.

**Comment by ideaweb** [comment]
Thats strange because the theme does not change anything in the browsing content, only in the "header". But i will check soon and let you know.

**Comment by tskucik** [comment]
Update: I noticed it only happens when using the dark Safari theme in windowed mode. 

Original Firefox theme works perfectly fine when in dark theme and windowed mode.

**Comment by kgorol** [comment]
Try enabling WebRender with command `gfx.webrender.all` set to true in about:config.

**Comment by tskucik** [comment]
> Try enabling WebRender with command `gfx.webrender.all` set to true in about:config.

It works! Thank you.

**Comment by thebitstick** [comment]
This seems to be fixed on the latest commit for me.
