### ISSUE TITLE
Rearranged Tabs aren't Rearranged

### ISSUE THREAD

**Issue by thebitstick** [ideaweb/firefox-safari-style#17]
When I rearrange a tab, Firefox will act like I did nothing at all, and when Ctrl+Tabbing, it shows the order of tabs I had before rearranging.

Firefox Nightly 85.0a1 on macOS Big Sur 11.0.1 running on a Mac Mini with Apple Silicon

**Comment by ideaweb** [comment]
It has been fixed in 0.2.8, please update and let me know if its working for you.

**Comment by thebitstick** [comment]
Fixed!
