### ISSUE TITLE
question: how to change private browsing purple defaults

### ISSUE THREAD

**Issue by this-fifo** [ideaweb/firefox-safari-style#19]
hey @ideaweb , thanks a lot for this theme, it quickly became my favourite !

do you know if there's an easy way to swap the purple used by private browsing mode? I noticed there's quite a lot of css using `[privatebrowsingmode]`, is there a variable or a central place where calculations are made around that purple tone?

**Comment by this-fifo** [comment]
I would also like to know if there's a way to make the website favicon appear next to the website title as opposed to the far left of the tab (looks closer to the Safari aesthetic)

**Comment by ideaweb** [comment]
Sorry for delay... added a new extra hint in README.md how to change the purple color. For the second question i'll check soon.

**Comment by this-fifo** [comment]
thank you so much for answering, I am not in a rush for the second one and it's also just a nice to have for me as I've become used to it being slightly different from Safari 🙏
