### ISSUE TITLE
Small amount of tabs are retained after restart

### ISSUE THREAD

**Issue by thebitstick** [ideaweb/firefox-safari-style#20]
Some tabs (like 10%) seem to close, but when using Ctrl/⌘+[0-9], they are still present, and will retain after restarting Firefox.

## Device
Firefox 85.0a1 on macOS 11.0.1 Big Sur

**Comment by ideaweb** [comment]
Yes, its an known issue. 

This themes changes only the Layout via CSS and does not change any functionallity e.g. via Javascript. But it seems that changing the layout causes, that Firefox does not remove closed tabs, just hiding them only. Restoring the sessions restores/displays such hidden tabs which is anoying. Without the theme, tabs will be removed from DOM immediately.

Seems that Firefox analyzes/evaluates nodes (e.g. position etc.) for some features and changing the layout causes unexpected behaviour... but just guessing... not easy to fix this issues with just CSS. 

But i keep an eye on it.

**Comment by sealvessel** [comment]
Perhaps could you make a branch 0.1 version with all of the node modification styles removed?

**Comment by sealvessel** [comment]
The main problem is that the native firefox shortcuts simply are not recognized properly; command-W simply hides the tab from DOM but command-T creates a new tab.
Using an extension such as any firefox vim extension causes the tab to actually be gone from DOM.
