### ISSUE TITLE
Broken in FF 84

### ISSUE THREAD

**Issue by fmccann** [ideaweb/firefox-safari-style#24]
MacOS 10.15.7 (19H114)
Firefox 84.0 (64-bit)
Theme: d87e798d4592b4490bc796981f4ec42a4266b958

Theme no longer works in Firefox 84. Screenshot attached. Maybe the names of tabs have changed? See attached image.

<img width="1687" alt="Screen Shot 2020-12-16 at 5 56 58 PM" src="https://user-images.githubusercontent.com/5367929/102416590-1c8ddb80-3fc8-11eb-94a5-80f485113e85.png">

**Comment by bhagatparwinder** [comment]
Well mine is far worse than yours on 84

**Comment by vnln** [comment]
yeah, light theme looks a lot better than dark one.

**Comment by lyubomir** [comment]
Firefox 84 removed `-moz-mac-yosemite-theme`. Replacing `(-moz-mac-yosemite-theme)` with `all` in css/userChrome.css seems to work for me as a quick workaround.

**Comment by ideaweb** [comment]
Right, -moz-mac-yosemite-theme has been removed recently in Firefox and i already added -moz-mac-big-sur-theme. But no idea if this works with Catalina. Did you already update your repository or does new -moz-mac-big-sur-theme is not working for you? Otherwise i will replace it with just "all". We talk about legacy version (branch 0.1) right?

**Comment by fmccann** [comment]
d87e798d4592b4490bc796981f4ec42a4266b958 on branch 0.1 isn't working for me on Catalina. I think maybe you need to use "all" or you can see the pull request that I made that seems to work (though I'm not sure that is actually better than using all).

**Comment by ideaweb** [comment]
Changed in 0.1, please try.

**Comment by cutieshy** [comment]
So, not sure what other people's result is but I'm seeing no change from default safari on Catalina with Version FF 84, I can import with the full blue as said in troubleshooting, but can't see any other changes

**Comment by ideaweb** [comment]
The master branch is for Big Sur, but if you still use Catalina Firefox will not show any changes. Did you switch to branch 0.1 to get legacy version?

``git checkout 0.1``

or just switch here in code view Github to branch 0.1 and press download.

**Comment by cutieshy** [comment]
> The master branch is for Big Sur, but if you still use Catalina Firefox will not show any changes. Did you switch to branch 0.1 to get legacy version?
> 
> `git checkout 0.1`
> 
> or just switch here in code view Github to branch 0.1 and press download.

Oh, thank you that was my fault then, works perfect!

**Comment by fmccann** [comment]
This working for me with the exception that the extra bit of css to not show the tab bar if there's only one tab isn't working anymore.

/* Only show tab bar if more than one tab */
#tabbrowser-tabs tab[first-visible-tab="true"][last-visible-tab="true"]:not([pinned]),
#tabbrowser-tabs tab[first-visible-tab="true"][last-visible-tab="true"]:not([pinned]) ~ toolbarbutton {
  visibility: collapse;
}
