### ISSUE TITLE
White line at top in full screen

### ISSUE THREAD

**Issue by eenbeterinternet** [ideaweb/firefox-safari-style#26]
There is a small thin line at the top of all full screen videos (YouTube, Netflix, etc). Is this intentional?
<img width="1536" alt="Screenshot 2021-01-14 at 22 37 55" src="https://user-images.githubusercontent.com/64610035/104652465-74982a80-56b9-11eb-953b-3737b1457fe7.png">

**Comment by ideaweb** [comment]
Fixed, please update.
