### ISSUE TITLE
Adding transparency/blur effect

### ISSUE THREAD

**Issue by semihcanturk** [ideaweb/firefox-safari-style#28]
Is it possible to edit the theme to enable some sort of transparency? The following example is a decent implementation of it: https://imgur.com/a/6IWDThn/

It's from the following userChrome.css, but I wasn't able to adapt it to this repo. Any help is much appreciated:
https://www.reddit.com/r/FirefoxCSS/comments/fbg0bv/safariesque_for_firefox_73_on_macos/

**Comment by ideaweb** [comment]
Its added, please check [README.md](https://github.com/ideaweb/firefox-safari-style).

**Comment by semihcanturk** [comment]
It seems like the vibrancy effect only applied to the tabs and not the main panel:
<img width="735" alt="image" src="https://user-images.githubusercontent.com/20279851/111450470-787c1380-8721-11eb-8127-f774fc18a359.png">
I pulled the latest master so I don't think that's the issue... any ideas?

**Comment by ideaweb** [comment]
I found a bug and hope this was the trouble maker. Please could you udpate and try again?

**Comment by semihcanturk** [comment]
Ah, I'm afraid not, still the same thing after updating. I'm adding a relative import at the start of css/UserChrome.css - that's how it should be, right?

```
/***************+**/
/* VERSION 0.2.18 */
/******************/
@import './userChrome-vibrancy.css';
/* Icons: resource://gre/chrome/toolkit/skin/classic/global/icons/ */
@namespace xul url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
@namespace html url("http://www.w3.org/1999/xhtml");
```

**Comment by semihcanturk** [comment]
Hey @ideaweb,
I saw that you made some additional changes, which seems to have fixed the issue partially:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/20279851/111611039-125cc280-87ed-11eb-8c95-41f95e5b4aaa.png">
The vibrancy effect still only applies to the tabs and not the main panel, but the tint is correct for light mode (previously it was the dark mode tint I believe, which rendered black text illegible). Another thing I mentioned is that no vibrancy effect occurs on the dark theme (may or may not be related). Let me know if you want me to test anything else - and many thanks!

**Comment by ideaweb** [comment]
Sorry for delay, i was not able to reproduce this issue. But now i think i get it.

Did you imported 2 files? Please import only one of these files. I mean, please do not import userChrome.css and  userChrome-vibrancy.css together. Please import userChrome-vibrancy.css only.

**Comment by semihcanturk** [comment]
I should import it in userChrome.css, right? I'm basically importing userChrome-vibrancy.css _only_ at the beginning of userChrome.css:
```
/***************+**/
/* VERSION 0.2.18 */
/******************/
@import './userChrome-vibrancy.css';
/* Icons: resource://gre/chrome/toolkit/skin/classic/global/icons/ */
@namespace xul url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
@namespace html url("http://www.w3.org/1999/xhtml");
```

**Comment by ideaweb** [comment]
Importing userChrome-vibrancy.css in userChrome.css of Firfox, not in userChrome.css of this theme.

Because in your code snippet in front of `@import './userChrome-vibrancy.css';` why there is "VERSION 0.2.18"? Why the extra @namespace? After @namespace is there any other lines of code? 

<img width="1196" alt="Screenshot 2021-03-19 at 14 02 30" src="https://user-images.githubusercontent.com/1529649/111784778-160b4a80-88bc-11eb-8bf4-a49fe1234e22.png">

**Comment by semihcanturk** [comment]
Ohhhh, my bad! I thought I was supposed to add the import statement at the start of the original userChrome.css which we import in the profile folder. Now that I changed the import statement in the profile to  userChrome-vibrancy.css, it works perfectly!

Thanks for the quick reply and your work, I'm loving this theme. Feel free to close the issue as well.
