### ISSUE TITLE
SSL padlock icon in address bar

### ISSUE THREAD

**Issue by zkvvoob** [ideaweb/firefox-safari-style#29]
Hello,

Would it be possible to align properly the padlock icon in the address bar?

<img width="602" alt="Screenshot 2021-02-16 at 11 11 39" src="https://user-images.githubusercontent.com/7645808/108041956-e44a5e00-7047-11eb-9746-4859bfb9a9e7.png">

Thanks!

**Comment by ideaweb** [comment]
Only to be sure, do you have the latest version? I ask, because some days ago i already fixed a similar issue.

Otherwise please could you tell me which Firefox version you're using and which file you included userChrome.css or userChrome-theme.css?

**Comment by zkvvoob** [comment]
I believe I'm using the latest version - did a `git pull` not 10 minutes before posting the issue. Using Firefox 85.0.2.

**Comment by ideaweb** [comment]
Fixed... please update (`git pull`) and try again.
