### ISSUE TITLE
Not working for FF 71.0b9 under MacOS 10.15.1

### ISSUE THREAD

**Issue by d4v1dv00** [ideaweb/firefox-safari-style#3]
There wasn't any userChrome.css file under profile folder by default, i added in and together with the line. Restarted FF and still the same as before. 

p.s. about:config changed

**Comment by ideaweb** [comment]
If nothing changed, then it could be that the userChrome.css file is not loaded.

Please could you add the following line to the end of userChrome.css file in your profile folder like:

```
@import '/Users/tom/Developer/firefox-safari-style/css/userChrome.css';
* { background-color: red !important; }
```

Then (re)start Firefox and the entire browser must be in "red". If so the userChrome.css file in your profile folder is working and you can revert your changes.

then please add the same line to the imported userChrome.css of this theme to verify that the imported file is loaded.

If in both cases the browser is shwon in "red" we must make other tests like verify that you imported the css file and not the scss file etc.

**Comment by mthuc** [comment]
It is not working for me on 71 release. My background color changes if I change to blue (for userChrome.css), so it is applying the changes. 

My userChrome.css:
```
➜  chrome cat userChrome.css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
@import '/Users/<user>/Downloads/firefox-safari-style/css/userChrome.css';
```

**Comment by dryshirt** [comment]
the @namespace line interferes with the @import statement, remove the @namespace line outside of userChrome.css and it works.
