### ISSUE TITLE
Firefox Dev 87.0b2 broke 0.1 tab text + icon alignment and url bar icons

### ISSUE THREAD

**Issue by mr-stezz** [ideaweb/firefox-safari-style#30]
Hey, I'm on Firefox Dev Edition (87.0b2) and the 0.1 branch (catalina theme) broke tab alignment of text and icons. 

![Screenshot 2021-02-25 at 10 37 46](https://user-images.githubusercontent.com/700472/109141467-ab03a380-7755-11eb-9a88-11531fc41a0d.png)

**Comment by ideaweb** [comment]
Please update and try again.

**Comment by mr-stezz** [comment]
Fixed, thank you 🙂
