### ISSUE TITLE
Flagfox extension squished together

### ISSUE THREAD

**Issue by iMonZ** [ideaweb/firefox-safari-style#37]
The Flags in the top bar with the Flagfox extension are squished together: https://ibb.co/P5LYW8L

Here is the link to the extension: https://addons.mozilla.org/en-US/firefox/addon/flagfox/

**Comment by ideaweb** [comment]
Changed in master branch, please update.

**Comment by iMonZ** [comment]
> Changed in master branch, please update.

Strange I got no notification about your comment.
But its fixed now :)
