### ISSUE TITLE
Overlapping text on tabs [FF Nightly 72 on 10.14.6]

### ISSUE THREAD

**Issue by Vash63** [ideaweb/firefox-safari-style#4]
<img width="1552" alt="Screen Shot 2019-11-14 at 13 37 58 " src="https://user-images.githubusercontent.com/3086017/68857985-5a913f80-06e4-11ea-835b-382699243b6f.png">

**Comment by Vash63** [comment]
Also noticed when looking at the screenshot but the marker of which container tab I'm using on the tab itself is missing, using Mozilla's official FF Container Tabs.

**Comment by ideaweb** [comment]
Fixed both issues.
