### ISSUE TITLE
Safari 15

### ISSUE THREAD

**Issue by iMonZ** [ideaweb/firefox-safari-style#44]
So Safari 15 got a huge redesign in the Tab bar.
Maybe there will be motivation to reimplement the redesign into this project.

**Comment by sarensabertooth** [comment]
I think putting the tabs dynamically in the same row as the address bar will be very difficult if not impossible. Since also the whole thing overflows. Maybe put the address bar fixed to the left and the tabs simply to the right, might be a good compromise.

**Comment by hacker1024** [comment]
People actually want this? If I was a Safari developer and Apple told me to build this UI I'd resign on the spot.

If this is implemented, could it be done in another branch? I'd be great if it was done in a way that meant most changes afterwards could still be applied to the old style, so both can be more easily patched to work with new Firefox releases.

**Comment by NetOperatorWibby** [comment]
I wouldn't mind this as an option but I have no idea how @ideaweb would be able to pull off the same functionality with a mere stylesheet.

**Comment by sarensabertooth** [comment]
> People actually want this? If I was a Safari developer and Apple told me to build this UI I'd resign on the spot.
> 
> If this is implemented, could it be done in another branch? I'd be great if it was done in a way that meant most changes afterwards could still be applied to the old style, so both can be more easily patched to work with new Firefox releases.

Unification is always a good thing, if executed well. Less elements means less confusion and less clutter and wasted space. Simple basic rule on which macOS lives and got great by.

**Comment by thebitstick** [comment]
This might be easier now due to Apple reverting the changes they made.
![image](https://user-images.githubusercontent.com/13919134/126051610-186d2a60-8f35-4cdd-a1ad-4490dd5fdc4e.png)

**Comment by sarensabertooth** [comment]
> This might be easier now due to Apple reverting the changes they made.
> ![image](https://user-images.githubusercontent.com/13919134/126051610-186d2a60-8f35-4cdd-a1ad-4490dd5fdc4e.png)

I keep hearing this. As someone who has the dev build installed, I can tell you they did not revert merely made it the default option. You can get the unified tab bar back by going to "View > Show Separate Tab Bar".
I think they even considered screen size, so on laptops the unified bar will be default and on desktop the old style is default. Or at least that's how it should be imo.
Somehow we can never get anything nice in safari and move onto something new. People have been complaining about changing the tab bar at all since Safari 4 Beta. Getting sick of it. Let the browser evolve.

**Comment by iMonZ** [comment]
> This might be easier now due to Apple reverting the changes they made.
> ![image](https://user-images.githubusercontent.com/13919134/126051610-186d2a60-8f35-4cdd-a1ad-4490dd5fdc4e.png)

On my own safari I use this option too and it’s looks so much better!

**Comment by NetOperatorWibby** [comment]
> This might be easier now due to Apple reverting the changes they made.

For what it’s worth, I think the change is hideous.

**Comment by github-account1111** [comment]
> People actually want this? If I was a Safari developer and Apple told me to build this UI I'd resign on the spot.

Of course they do.
It saves precious vertical space without any sacrifice.
Unless you're a tab hoarder, in which case, have you heard of bookmarks?

**Comment by sarensabertooth** [comment]
> > People actually want this? If I was a Safari developer and Apple told me to build this UI I'd resign on the spot.
> 
> Of course they do. It saves precious vertical space without any sacrifice. Unless you're a tab hoarder, in which case, have you heard of bookmarks?

Or tab groups :P

**Comment by ideaweb** [comment]
> People actually want this? If I was a Safari developer and Apple told me to build this UI I'd resign on the spot.

Yes, they want. E.g. in closed Beta of Orion Browser, there is a big discussion about implementing compact tabs. Developers decline it, but most users seems to want it. Never thought it....

Anyway, I like the idea, and that Apple made it optional that users can decide. But CSS is very limited and I think its not possible to add such functionality.
