### ISSUE TITLE
How is the support for Firefox 89?

### ISSUE THREAD

**Issue by sealvessel** [ideaweb/firefox-safari-style#46]
I want some opinions on whether or not this css style completely breaks on the new Firefox proton 89 release. Thanks.

**Comment by nchlscs** [comment]
I use on 89 with some custom tweaks, looks well
<img width="1386" alt="ff" src="https://user-images.githubusercontent.com/50764345/124344623-cfccc380-dbec-11eb-83a7-d408fe822ef4.png">

**Comment by ideaweb** [comment]
I work with Firefox Nightly and on problems/changes I try to fix it asap like new introduced gui/tabs. Means if you using a stable release you can always update Firefox. But of course on trouble dont forget to to update the theme as well to get recent fixes/changes.
