### ISSUE TITLE
Hide elements in the URL bar

### ISSUE THREAD

**Issue by hjstephens09** [ideaweb/firefox-safari-style#5]
Hey there. First off, thanks for taking the time to create this awesome userChrome.css. It's hands down the best Safari clone of Firefox I've ever used. I'm seriously blown away how integrated the look is into Firefox.

My question is: Would it be possible to include some optional code to hide 'unneeded' elements in the URL bar?

Here's what I normally run in my userChrome.css that allows me to hide — among other things — FF tracking protection icon and the secure padlock, which is my preference:

> /**** Hide Firefox Tracking Protection badge ****/
> #tracking-protection-icon-box {visibility: collapse !important;}
> #tracking-protection-icon-container {display: none;}
> 
> /**** Remove unnecessary identity-box content ****/
> #urlbar[pageproxystate="valid"] > #identity-box.verifiedDomain > #connection-icon,
> #urlbar[pageproxystate="valid"] > #identity-box.verifiedIdentity > #connection-icon,
> #urlbar[pageproxystate="valid"] > #identity-box.mixedActiveBlocked > #connection-icon,
> #urlbar[pageproxystate="valid"] > #identity-box.verifiedIdentity > #identity-icon-labels {
>   display: none !important;
> }
> #urlbar[pageproxystate=valid] > #identity-box.notSecureText,
> #urlbar[pageproxystate=valid] > #identity-box.verifiedIdentity,
> #urlbar[pageproxystate=valid] > #identity-box.chromeUI,
> #urlbar[pageproxystate=valid] > #identity-box.extensionPage,
> #urlbar[pageproxystate=valid] > #identity-box[pageproxystate="valid"].certUserOverridden > #identity-icon,
> .drm-icon {
>   display: none !important;
> }
> #urlbar-display-box {
>   border: none !important;
>   margin-right: 0 !important;
> }

The above code doesn't work with your userChrome.css. Between me not knowing hardly anything about CSS and the document having so many elements, I don't know where to begin troubleshooting. This is the first time that I've had an issue with hiding elements in the URL bar.

Thanks for looking into this!

**Comment by ideaweb** [comment]
Sorry for delay....

Please could me send your entire userChrome.css located in your profile folder? I mean with your changes and the line with the import of this theme. I'll check locally.

**Comment by hjstephens09** [comment]
This is no longer an issue for me. How I got around this was removing my code from the `userChrome.css` file and instead adding an `@import url(chrome/hide_elements.css)`.

I also forced the prefs by adding `!important;`

> /* URL Bar */
> #tracking-protection-icon-container {display:none;}
> #blocked-permissions-container {display:none;}
> #identity-box.verifiedDomain #identity-icon {display:none !important;}
> .autocomplete-history-dropmarker {display:none !important;}
> .urlbar-history-dropmarker.urlbar-icon.chromeclass-toolbar-additional {display:none !important;}
> #reader-mode-button {display:none !important;}
> #pageActionSeparator {display:none !important;}
