### ISSUE TITLE
About the firefox100 version dark mode does not display properly

### ISSUE THREAD

**Issue by Zranshi** [ideaweb/firefox-safari-style#50]
After the upgrade of firefox to 100, due to the addition of the website appearance option to firefox, all userChrome files cannot display the dark mode interface properly after changing to dark mode.

When the picture is displayed, it is in dark mode, but the interface is still bright, and there are errors in the selection shadow and font color in the address bar.

<img width="2001" alt="图片" src="https://user-images.githubusercontent.com/46834813/166905545-2f051c0e-3abc-4373-92e6-2109f1be84b1.png">

I guess it may be because userChrome cannot correctly identify whether the firefox has been changed to dark mode after upgrading to firefox100, resulting in not successfully changing to dark mode. Has the author considered supporting firefox100?

**Comment by ideaweb** [comment]
I tried to make a fix for dark mode and vibrancy theme files. Please update and try again.

**Comment by shahmilav** [comment]
I tried the vibrancy theme file, looks great! Thanks
