### ISSUE TITLE
Tab icons are slightly out of place when pinned.

### ISSUE THREAD

**Issue by lazerl0rd** [ideaweb/firefox-safari-style#58]
As shown by the image below...

![image](https://github.com/ideaweb/firefox-safari-style/assets/24303423/33328ceb-c2e3-4772-a799-37a7a2841c14)

...pinned tab icons seem to be positioned a few pixels too low, but more importantly the new tab icon looks completely out of place (too high up and too much to the right).

**Comment by ideaweb** [comment]
Please update and try again.
