### ISSUE TITLE
Reopens Two to Three tabs from history when "Restore Previous Session" is checked

### ISSUE THREAD

**Issue by yokoffing** [ideaweb/firefox-safari-style#6]
If the user did not leave anything open from his previous session while "Restore previous session" was enabled, the browser opens two New Tab pages.

**Comment by ideaweb** [comment]
I think this is not an issue of this theme. Because this code just uses CSS to theme the layout, colors and font. There is not any proccessing code like Javascript. Only Firefox itself and browser extensions can control tabs like opening new ones, but not this theme.

**Comment by yokoffing** [comment]
> I think this is not an issue of this theme. Because this code just uses CSS to theme the layout, colors and font. There is not any proccessing code like Javascript. Only Firefox itself and browser extensions can control tabs like opening new ones, but not this theme.

I have several different Firefox profiles with the same browser settings, and have tested this theme multiple times on different profiles. This is the only userChrome theme I've had that does this.
