### ISSUE TITLE
userChrome-vibrancy.css titlebar is completely transparent since FF122.0

### ISSUE THREAD

**Issue by stevehartwell** [ideaweb/firefox-safari-style#60]
Since Firefox 122 or so, `userChrome-vibrancy.css` renders the window title bar completely transparent, instead of a barely translucent background.

Removing the `background-color: transparent !important;` styling from the `#main-window` and related elements seems to fix the problem.

<img width="754" alt="userChrome-vibrancy" src="https://github.com/ideaweb/firefox-safari-style/assets/7692279/0ca6ea15-1b4b-467a-b782-080da3ed637c">

**Comment by stevehartwell** [comment]
stale.

**Comment by NetOpWibby** [comment]
Damn
