### ISSUE TITLE
Center bookmarks?

### ISSUE THREAD

**Issue by AndroidKitKat** [ideaweb/firefox-safari-style#7]
I don't know if this is possible, but centering the bookmarks on the bookmarks bar would be one more step closer to this being the perfect Safari replacement. 

I did a little digging around and found this: https://highvaluedaygame.com/my-firefox-css/, which is another attempt to make Firefox more Safari-like. Don't know if it would be any use, but figured I'd leave it there.

Thanks for making this, I really love it.

**Comment by ideaweb** [comment]
Added... please update.
